run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/standup-raven/standup-raven/server
  golint:
    min-confidence: 0
  govet:
    check-shadowing: true
    enable-all: true
  misspell:
    locale: US
  gocritic:
    disabled-checks:
      - ifElseChain

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - gocritic
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace

issues:
  exclude:
    - 'declaration of "(err|ctx)" shadows declaration at'
  exclude-rules:
    - path: server/manifest.go
      linters:
        - deadcode
        - unused
        - varcheck
    - path: server/configuration.go
      linters:
        - unused
    - path: _test\.go
      linters:
        - bodyclose
        - scopelint # https://github.com/kyoh86/scopelint/issues/4
